# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ros2_validation_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 18 * * *' # Daily @ 10AM PST (UTC)
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ros:humble

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y python3-pip
        pip3 install --upgrade pip
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Build ros2 package
      run: |
        . /opt/ros/humble/setup.sh
        colcon build
    - name: Run tests
      run: |
        . /opt/ros/humble/setup.sh
        . install/setup.sh
        ros2 run validation_suite battery_publisher.py & ros2 run validation_suite imu_publisher.py &
        ros2 run validation_suite odometry_publisher.py & sleep 5
        python3 -m pytest -v --junitxml=report.xml
    - name: export test metrics
      env:
        OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.GRAFANA_OTLP_ENDPOINT }}
        OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.GRAFANA_OTLP_HEADERS }}
      run: | 
        python3 juni_to_open.py report.xml
